// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_EXaKs7gOIY7wVQJhh8giz6LuAQbor6k',
    appId: '1:1081994605734:web:7657924021ecd62f4cf067',
    messagingSenderId: '1081994605734',
    projectId: 'minimal-social-app-ab32a',
    authDomain: 'minimal-social-app-ab32a.firebaseapp.com',
    storageBucket: 'minimal-social-app-ab32a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHhMafZQgcI80zgWoHYCka411ttpslojI',
    appId: '1:1081994605734:android:381c1843c1ad8d8d4cf067',
    messagingSenderId: '1081994605734',
    projectId: 'minimal-social-app-ab32a',
    storageBucket: 'minimal-social-app-ab32a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-MNmrE4cbEMWtxvRYNmPpowtmnzna-ys',
    appId: '1:1081994605734:ios:e1f378cf2f758d4c4cf067',
    messagingSenderId: '1081994605734',
    projectId: 'minimal-social-app-ab32a',
    storageBucket: 'minimal-social-app-ab32a.appspot.com',
    iosBundleId: 'com.example.minimalsocialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-MNmrE4cbEMWtxvRYNmPpowtmnzna-ys',
    appId: '1:1081994605734:ios:45be10e19e53e7bc4cf067',
    messagingSenderId: '1081994605734',
    projectId: 'minimal-social-app-ab32a',
    storageBucket: 'minimal-social-app-ab32a.appspot.com',
    iosBundleId: 'com.example.minimalsocialApp.RunnerTests',
  );
}
